# Generated by Django 4.2.20 on 2025-04-09 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='articel',
            new_name='article',
        ),
    ]
