# Generated by Django 4.2.2 on 2025-03-27 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0002_rename_category_name_book_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='category_id',
            new_name='salesPoint',
        ),
    ]
